language: java
sudo: false
before_script: cd CaulCrafting
before_install:
  - git clone -P jars/ http://dariusmtn.fr/caulcrafting/Spigot-1.12.jar
  - mvn validate
  - wget -P jars/ http://dariusmtn.fr/caulcrafting/Spigot-1.11.jar
  - mvn validate
  - wget -P jars/ http://dariusmtn.fr/caulcrafting/Spigot-1.10.jar
  - mvn validate
  - wget -P jars/ http://dariusmtn.fr/caulcrafting/Spigot-1.9_R1.jar
  - mvn validate
  - wget -P jars/ http://dariusmtn.fr/caulcrafting/Spigot-1.9_R2.jar
  - mvn validate
notifications:
  email: false
deploy:
  provider: releases
  api-key: ${GITHUB_TOKEN}
  file:
  - target/CaulCrafting.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
