language: java
sudo: false
before_script: cd CaulCrafting
notifications:
  email: false
deploy:
  provider: releases
  api-key: ${GITHUB_TOKEN}
  file:
  - target/CaulCrafting.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
