language: java
sudo: false
before_script: cd CaulCrafting
before_start:
  - mkdir lib/
  - wget -P "lib/" http://dariusmtn.fr/caulcrafting/spigotjar/Spigot-1.12.jar
  - wget -P "lib/" http://dariusmtn.fr/caulcrafting/spigotjar/Spigot-1.11.2.jar
  - wget -P "lib/" http://dariusmtn.fr/caulcrafting/spigotjar/Spigot-1.10.jar
  - wget -P "lib/" http://dariusmtn.fr/caulcrafting/spigotjar/Spigot-1.9_R1.jar
  - wget -P "lib/" http://dariusmtn.fr/caulcrafting/spigotjar/Spigot-1.9_R2.jar
notifications:
  email: false
script: ant build
