#Config version, it's only serve to convert with a config update in the future <3 
config_version: 2

#Display all the plugin actions on logs
debug_message: false

#What language do you want to use ? ;)
#Check "config_locale.yml"

